# Generated by Django 5.0.6 on 2024-07-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Введите тему сообщения', max_length=100, verbose_name='Тема коммуникации')),
                ('body', models.TextField(help_text='Введите текст сообщения', verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('pk',),
            },
        ),
    ]
