# Generated by Django 5.0.6 on 2024-07-28 14:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_attempt', models.DateTimeField(default=datetime.datetime(2024, 7, 28, 17, 33, 41, 933337), help_text='Введите дату и время первой рассылки. По умолчанию - текущее время', verbose_name='Дата и время первой рассылки')),
                ('date_time_threshold', models.DateTimeField(default=datetime.datetime(2024, 7, 28, 17, 33, 41, 933361), help_text='Введите дату и время окончания рассылок. По умолчанию - текущее время', verbose_name='Дата и время окончания периода')),
                ('period', models.IntegerField(choices=[(60, 'Раз в минуту'), (180, 'Раз в 3 минуты'), (300, 'Раз в 5 минут')], default=(300, 'Раз в 5 минут'), help_text='Укажите периодичность рассылки', verbose_name='Период рассылки')),
                ('status', models.CharField(default='В ожидании', max_length=100)),
                ('client', models.ManyToManyField(related_name='mailings', to='clients.client')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.communication')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_last_attempt', models.DateTimeField(default=datetime.datetime(2024, 7, 28, 14, 33, 41, 947321, tzinfo=datetime.timezone.utc), verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(default='Не отправлялось', max_length=50, verbose_name='Статус рассылки')),
                ('server_code_response', models.IntegerField(blank=True, null=True, verbose_name='Номер рассылки')),
                ('server_response', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Ответ от сервера')),
                ('mailing_relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailing')),
            ],
            options={
                'verbose_name': 'статус рассылки',
                'verbose_name_plural': 'статусы рассылок',
            },
        ),
    ]
