# Generated by Django 5.0.6 on 2024-08-13 20:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_attempt', models.DateTimeField(default=datetime.datetime(2024, 8, 13, 23, 24, 45, 471841), help_text='Введите дату и время первой рассылки. По умолчанию - текущее время', verbose_name='Дата и время первой рассылки')),
                ('date_time_threshold', models.DateTimeField(default=datetime.datetime(2024, 8, 13, 23, 24, 45, 471868), help_text='Введите дату и время окончания рассылок. По умолчанию - текущее время', verbose_name='Дата и время окончания периода')),
                ('period', models.IntegerField(choices=[(86400, 'Раз в день'), (604800, 'Раз в неделю'), (2592000, 'Раз в месяц')], default=(2592000, 'Раз в месяц'), help_text='Укажите периодичность рассылки', verbose_name='Период рассылки')),
                ('status', models.CharField(default='В ожидании', max_length=100, verbose_name='Статус рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус рассылки')),
                ('client', models.ManyToManyField(related_name='mailings', to='clients.client', verbose_name='Клиент рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.communication', verbose_name='Сообщение рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('pk',),
                'permissions': [('view_any_mailing', 'Может просматривать любые рассылки'), ('disable_mailing', 'Может отключать рассылки')],
            },
        ),
    ]
