# Generated by Django 5.0.6 on 2024-08-04 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_time_last_attempt',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 17, 39, 6, 209348, tzinfo=datetime.timezone.utc), verbose_name='Дата и время последней попытки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_time_attempt',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 20, 39, 6, 195706), help_text='Введите дату и время первой рассылки. По умолчанию - текущее время', verbose_name='Дата и время первой рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_time_threshold',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 20, 39, 6, 195736), help_text='Введите дату и время окончания рассылок. По умолчанию - текущее время', verbose_name='Дата и время окончания периода'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='period',
            field=models.IntegerField(choices=[(60, 'Раз в минуту'), (180, 'Раз в 3 минуты'), (300, 'Раз в 5 минут')], default=(300, 'Раз в 5 минут'), help_text='Укажите периодичность рассылки', verbose_name='Период рассылки'),
        ),
    ]
