# Generated by Django 5.0.6 on 2024-07-28 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_log_date_time_last_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_time_last_attempt',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 15, 28, 21, 533155, tzinfo=datetime.timezone.utc), verbose_name='Дата и время последней попытки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_time_attempt',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 18, 28, 21, 519200), help_text='Введите дату и время первой рассылки. По умолчанию - текущее время', verbose_name='Дата и время первой рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_time_threshold',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 18, 28, 21, 519222), help_text='Введите дату и время окончания рассылок. По умолчанию - текущее время', verbose_name='Дата и время окончания периода'),
        ),
    ]
