# Generated by Django 5.0.6 on 2024-08-04 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_log_date_time_last_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_time_last_attempt',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 18, 8, 17, 434276, tzinfo=datetime.timezone.utc), verbose_name='Дата и время последней попытки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_time_attempt',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 21, 8, 17, 420897), help_text='Введите дату и время первой рассылки. По умолчанию - текущее время', verbose_name='Дата и время первой рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_time_threshold',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 21, 8, 17, 420927), help_text='Введите дату и время окончания рассылок. По умолчанию - текущее время', verbose_name='Дата и время окончания периода'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='period',
            field=models.IntegerField(choices=[(86400, 'Раз в день'), (604800, 'Раз в неделю'), (2592000, 'Раз в месяц')], default=(2592000, 'Раз в месяц'), help_text='Укажите периодичность рассылки', verbose_name='Период рассылки'),
        ),
    ]
