# Generated by Django 5.0.6 on 2024-08-03 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailing_options_mailing_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_time_last_attempt',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 13, 59, 38, 566826, tzinfo=datetime.timezone.utc), verbose_name='Дата и время последней попытки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_time_attempt',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 16, 59, 38, 553446), help_text='Введите дату и время первой рассылки. По умолчанию - текущее время', verbose_name='Дата и время первой рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_time_threshold',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 16, 59, 38, 553476), help_text='Введите дату и время окончания рассылок. По умолчанию - текущее время', verbose_name='Дата и время окончания периода'),
        ),
    ]
