# Generated by Django 5.0.6 on 2024-08-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateTimeField(auto_created=True, verbose_name='Дата создания статьи')),
                ('title', models.CharField(help_text='Введите заголовок', max_length=150, verbose_name='Заголовок')),
                ('body_blog', models.TextField(help_text='Введите текст статьи', verbose_name='Содержимое статьи')),
                ('picture', models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='blog/', verbose_name='Фото')),
                ('count_view', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ('pk',),
            },
        ),
    ]
