# Generated by Django 5.0.6 on 2024-08-04 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 4, 20, 39, 6, 210085), verbose_name='Дата создания статьи'),
        ),
    ]
