# Generated by Django 5.0.6 on 2024-08-03 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 3, 17, 2, 12, 712019), verbose_name='Дата создания статьи'),
        ),
    ]
