# Generated by Django 5.0.6 on 2024-08-04 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 4, 21, 8, 17, 434931), verbose_name='Дата создания статьи'),
        ),
    ]
