# Generated by Django 5.0.6 on 2024-08-13 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_last_attempt', models.DateTimeField(default=datetime.datetime(2024, 8, 13, 20, 24, 45, 497519, tzinfo=datetime.timezone.utc), verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(default='Не отправлялось', max_length=50, verbose_name='Статус рассылки')),
                ('server_code_response', models.IntegerField(blank=True, null=True, verbose_name='Номер рассылки')),
                ('server_response', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Ответ от сервера')),
            ],
            options={
                'verbose_name': 'статус рассылки',
                'verbose_name_plural': 'статусы рассылок',
                'ordering': ('pk',),
            },
        ),
    ]
